### ISSUE TITLE
Return city/town of publication.

### ISSUE THREAD

**Issue by EvansMike** [xlcnd/isbnlib#25]
Amongst other data wcat (probably others too but I've only ever used worldcat) returns city of publication, this should be passed back to the caller too.

**Comment by xlcnd** [comment]
Thanks for your suggestion.

In early versions of `isbnlib`, City and Language were part of the standard set of metadata fields. However,  they were deleted from the supported set of fields, because the poor quality of the data for these fields (Language was kept at provider level but is not supported downstream).

Is my intention to rewrite the way these standard metadata fields are handled (now they are hard coded in several places) in order to provide some support to people who need more fields.

**Comment by xlcnd** [comment]
Let me add the following suggestion, if you need City badly, then make a new provider, lets us say `wcat2`, and use `isbnlib.registry` to make it available inside `isbnlib`. In this way you get some facilities, like caching, provided by `isbnlib`.
