### ISSUE TITLE
Edition / Format

### ISSUE THREAD

**Issue by Spazzolino** [xlcnd/isbnlib#27]
Hi, I have a problem similar to EvansMike.
When submitting a request, I would like to get info on the edition and the format, together with the other metadata. 

I was trying to create, as it was suggested, a second provider ('wcat2') and to adapt it to the extra data I'd like to get. 

I therefore created *wcat2.py* addig two lines

>canonical['Edition'] = records.get('ed', u(''))
>canonical['Format'] = records.get('form',u(''))

Then I ran:

>isbnlib.registry.ass_service('wcat2', 'isbnlib\_wcat2.py')

The issue I'm having now is to make it work. I also modified the file *_data.py* to include the two extra fields I need. 

Still, it's not working. At the moment I'm getting **NotValidMetadataError**.

I have two questions: 
first, what would be the procedure? Do you have any suggestion on how to proceed?
second: why aren't these fields included? Is it due to problems with quality/availability?

Thank you in advance!

**Comment by xlcnd** [comment]
Thank you for your interest in using *isbnlib*.

Answering your questions:

**first, what would be the procedure?**
The procedure is more or less what you have done... but you are making some mistakes. In your program, you must have `import wcat2`  (I suppose you follow the pattern of `wcat` and that your file with the new provider is `wcat2.py`), then after importing `isbnlib` you must register your service `isbnlib.registry.add_service('wcat2', wcat2.query)`. In `wcat2.py` you must add the new fields to the SERVICE_URL, so `SERVICE_URL=...&fl=...,lang,form,ed` together with what you have already done. Then go to `_data.py` and include in `FIELDS = (..., 'Edition', 'Format')`. Finally, go to *_fmt.py* and figure out how to insert the new fields in the bibliographic formats!

**second: why aren't these fields included?  Is it due to problems with quality/availability?**
Quality yes. For USA books is not bad, but outside USA is terrible. The goal of *isbnlib* is to provide a core of high quality metadata for any book in the world.

**Comment by Spazzolino** [comment]
Thank you a lot for the clarifications!

2015-11-21 18:28 GMT+01:00 Alexandre Conde <notifications@github.com>:
