### ISSUE TITLE
notisbn does not invalidate all not ISBNs

### ISSUE THREAD

**Issue by Phyks** [xlcnd/isbnlib#35]
Hi,

```
>>> isbnlib.notisbn("9783161484100aa")
False
```

Is it expected? Reading the doc, I would have said that such an ISBN would be rejected.

Thanks

**Comment by xlcnd** [comment]
Yes, it is expected. The idea behind 'notisbn' is to detect strings from which we cannot extract valid isbns.

So, since we *can* extract a valid isbn from string ' 9783161484100aa' it returns 'False'.

**Comment by Phyks** [comment]
Ok. Do you see a straightforward way to validate the full string as an ISBN with the library as is?

**Comment by xlcnd** [comment]
Yes. The best approach depends on the context, but you can use 'get_canonical_isbn' or 'ean13'.

**Comment by Phyks** [comment]
Actually not, or I misunderstood.

My goal is to validate ISBNs like this:
```python
    >>> is_valid("978-3-16-148410-0")
    True

    >>> is_valid("9783161484100")
    True

    >>> is_valid("9783161484100aa")
    False

    >>> is_valid("abcd")
    False

    >>> is_valid("0136091814")
    True

    >>> is_valid("0136091812")
    False

    >>> is_valid("9780136091817")
    False

    >>> is_valid("123456789X")
    True
```

I am currently using `not isbnlib.notisbn(isbn))` but it fails on "9783161484100aa". According to your latest comment, I thought about using something like
```python
((not isbnlib.notisbn(isbn)) and (isbnlib.get_isbnlike(isbn) == isbn))
```

but this time, it fails on "978-3-16-148410-0" because the `get_isbnlike` function does not gives the same ISBN representation (no dashes).

Thanks!

**Comment by xlcnd** [comment]
Do you want to validate the mask too? 

For example: "978-3-16-148410-0" must be True and "978-3-16148410-0" False.

**Comment by Phyks** [comment]
If possible, that would be even better. Actually I'd like to validate a string against an ISBN, to make sure that this string, *as is*, is a valid representation of an ISBN.

**Comment by xlcnd** [comment]
There is no function in the library that does that. Why? Because it is not a good idea...

For isbn-international.org a valid ISBN is something **exactly of the form** 'ISBN  978-3-16-148410-0' (**and** that have been issued already). However the publishers don't respect that and use almost all variations possible! 

'isbnlib' uses the concept of 'canonical' isbn (only numbers and 'X') and validates that according to the ISBN's sum rules.

However is not difficult to create a function that 'validates' ISBNs according to some other rules.

**Comment by Phyks** [comment]
Ok, works great! Thanks!
