### ISSUE TITLE
Clear socket setdefaulttimeout side effects.

### ISSUE THREAD

**Issue by mihaibivol** [xlcnd/isbnlib#43]
It seems that the `setdefaulttimeout` call in `config.py` has ugly side effects when used in a `Flask` application with `DEBUG = True`.

Is there any reason for using this instead of the urlopen timeout parameter?

**Comment by xlcnd** [comment]
As far as remember, I didn't use _urlopen timeout_ for two reasons:
1. I try initially to support python 2.5 (is not the case anymore...).
2. Problems when used with another framework (django ?.?).

I will reanalyse the situation and see what I can do for the next major release, but for now I can't change it, it would broke the api...

Anyway, usually these 'side effects' disappear if you do a 'dummy' call to _isbnlib_ as early as possible in the stack.

**Comment by xlcnd** [comment]
**Another suggestion**:

Have you tried to increase the value of SOCKETS_TIMEOUT (some of these web frameworks need to have sockets open for a long time)?

**Comment by mihaibivol** [comment]
Thanks for the quick response and suggestions.

Our project uses `isnblib` indirectly, through another dependency. It might be tricky to force the config loading since we actually needed for hyphenating isbn numbers.

I can also provide a way for reproducing the issue. Maybe it will help you in evaluating this issue:

* Start from Flask Hello World http://flask.pocoo.org/docs/0.11/quickstart/
* Instead of 'Hello World' use something like `<img src="/static/some_image_you_serve">`
* Import isbnlib somewhere before defining the route

If you start the server and go to `localhost:5000` the app debug log should show something like `errno 11` for Linux hosts or `errno 35` for Mac ones.

**Comment by mihaibivol** [comment]
I added the regression test here https://github.com/mihaibivol/isbnlib-flask-error-demo

**Comment by xlcnd** [comment]
I followed your instructions (https://github.com/mihaibivol/isbnlib-flask-error-demo) to replicate the problem.

I tested it in my [local]  Ubuntu 14.04 system and ... I got a nice tux image! 

Then I tested it with a server (running debian jessie) and used my local browsers (chrome and firefox). Again I got a nice tux image!

**I am not able to reproduce the problem**.

And I must say, your error is very strange, if Flask is not able to serve a local resource in 11 seconds (SOCKETS_TIMEOUT by default) then something very bad is happen with that Flask setup (permissions?)!

Usually the problem with SOCKETS_TIMEOUT is that is small for some web frameworks when they serve heavy resources from other servers *in direct mode* . But they set their own SOCKETS_TIMEOUT late in the stack so that it overwrites any previous value and in that way causing some problems **to** ``isbnlib`` when it uses external web services!

Another relevant parameter is THREADS_TIMEOUT, but again is usually overwritten by the framework.

There must be something else ... and, from your example to reproduce the problem, I must say that is something very peculiar to your system (!?). For example, some 'sand-boxed' systems (SUSE, XOS) come with configurations that don't allow the packages to access some files of the 'user space', creating some very strange behaviour if permissions are not properly handled by the installer. Even if you install packages inside a virtual environment you could get these kind of behaviours (if you use an old version of pip...), but this is only a guess for your case.

**Comment by mihaibivol** [comment]
This problem only appears only in debug mode and it doesn't always surface.
The Flask DEBUG mode works by creating two processes via the Fork mechanism. One is the one actually serving requests while the other uses some `inotify` mechanism for reloading the server if the code changes. The imports are being run for both processes, so maybe there's some race condition caused by `setdefaulttimeout`. We also have this error reproduced on Mac and @jacquerie reproduced it for another library that uses `setdefaulttimeout` using the same Flask skel.

Given that this is a transient error, can you also try again, and also serve more than one image on page load.

**Comment by xlcnd** [comment]
But 11 seconds is plenty of time! 

I am running a script driving the browser to periodically call a small RPi server and at the same time I have another script 'changing the code' in the server, until now its OK,  but let's keep it running...

**Comment by jacquerie** [comment]
FWIW, I confirm 100% what @mihaibivol is saying. I have a recent Mac OS with recent `pip` (8.1.2) and I see the same issue. I will try setting up a VirtualBox machine with Ubuntu 14.04 inside and see what happens.

**Comment by xlcnd** [comment]
I continue not be able to reproduce the error... but if the problem is the use of  ``setdefaulttimeout`` by ``isbnlib``then we have a problem! SOCKETS_TIMEOUT is exposed in the API of the library and several projects use this feature!  I cannot change this  without creating problems on some of those projects. [The use of the parameter timeout in urlopen is NOT completely equivalent]. 

Since the dependence on ``isbnlib`` is thru another package, I am not seeing a solution for now.

**Comment by xlcnd** [comment]
Next week I will release isbnlib-3.6.1 in order to reflect some big changes in the web services.  Some maintenance releases will follow in the next months. I will put a notice that by version 3.7.1 (October/November) I will use timeout in urlopen instead of setdefaulttimeout.

**Comment by mihaibivol** [comment]
I also made a Travis build for replicating the bug and a test script using `phantomjs`
https://travis-ci.org/mihaibivol/isbnlib-flask-error-demo/builds/138125320

If you open any pull requests against the test repo you can trigger this build.

**Comment by mihaibivol** [comment]
I also added a build that runs the test case 5 times. You can see here https://travis-ci.org/mihaibivol/isbnlib-flask-error-demo/builds/138128020 that the behavior is transient.

**Comment by xlcnd** [comment]
I see... but I continue running without errors in my systems (I am using python 3). 

Anyway, if the problem is the use of ``setsocketstimeout`` (a potentially problematic but fair use in python), as I said above, I cannot do anything for now. I am sorry!

However, as far as I understood, you depend on ``isbnlib`` thru  a third package and all you need is to hyphenate an ISBN? In that case, who loads ``isbnlib``?

**Comment by jacquerie** [comment]
In our case it's a library we own called `idutils`. In fact, since we own it, we can easily fall back to another library, like this PR does: https://github.com/inveniosoftware/idutils/pull/9

**Comment by xlcnd** [comment]
@jacquerie OK, problem solved.

**Comment by xlcnd** [comment]
Can someone do the test with the version of ``isbnlib`` on the _dev_ branch?

**Comment by xlcnd** [comment]
@mihaibivol I presume that the third package is ``idutils`` too? If so, then I am glad that the problem is solved. Doesn't make sense to use ``isbnlib`` just to hyphenate an ISBN. There are a lot of small libraries to do that.

**Comment by mihaibivol** [comment]
@xlcnd `idutils` solves our problem (it hyphenates ISBN10 in its ISBN13 form but we can live with that). Thanks for the quick responses :)

**Comment by mihaibivol** [comment]
@xlcnd I also added a build for the `dev` branch https://travis-ci.org/mihaibivol/isbnlib-flask-error-demo/branches. I saw another error but this might be caused by some timeout issues. Feel free to submit any PRs to trigger the build or to add other python versions.

**Comment by xlcnd** [comment]
I create a branch (**TEST_flask**) with a special version of _isbnlib_ that **doesn't use** ``socket.setdefaulttimeout`` and a branch ( **TRAVIS_flask**) that test it on Travis together with Flask. 

People can test it locally within they projects if they put in _requirements.txt_ https://github.com/xlcnd/isbnlib/archive/TEST_flask.zip.

**By version 3.7.1 these changes will make it in the normal version of _isbnlib_**.
