### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by latkins** [xlcnd/isbnlib#50]
I'm experimenting with this library to clean up a large-ish (~100k) list of ISBNs that I have. I would like to find the EAN for each, extract a list of previous editions, the meta data, and a description. Doing the naive thing results in google books giving a 403 after ~10 ISBNs. 

The docs mention it is possible to do things in a more batched way - is there an example of this? Also, I believe I have set my API key for google books, but am not sure. Is there a way to check I have done so correctly (I used `isbnlib.config.set_apikey('goob', <MYKEY>)`)?

**Comment by xlcnd** [comment]
Thank you for your interest in `isbnlib`.

- The 403 errors are due to the *too much calls by second* that you are making to the service! Google Books doesn't allow more than one call per second and only 1000 calls per day (per ip).  The library implements a throttling mechanism with a default rate of one call per second per service **per process**. So to avoid this error you must respect these requirements! Are you using more than one process or thread?
- There are many ways to implement a *long running batch process*. The simpler is just put the ISBNs in a queue (or list) and make calls to services 'as usual', but cache the 403 errors (catch exception `isbnlib.dev.ISBNLibHTTPError`). As soon as you get the error just wait 20 minutes and continue. Don't use more than one thread or process! 
- The part of Google Books used by `isbnlib` **doesn't** need (or use) a key! But for services that need a key you are right, that is the code to use before call `isbnlib.meta(isbn, service='<service_id>')`.

**Comment by latkins** [comment]
Thanks for your reply! I suppose I will, for now, limit myself to non google-books APIs, and just set it going. I expect that the 100k can be reduced by removing ISBNs that are associated (by edition) of a previous ISBN.

Thanks again for your response.
