### ISSUE TITLE
ISSN support

### ISSUE THREAD

**Issue by azmeuk** [xlcnd/isbnlib#63]
Hi,
I could not find any mention of [ISSN](https://www.issn.org/understanding-the-issn/what-is-an-issn/) in this repository, so I open this ticket to discuss it. This a ISBN for periodicals.
Is there maybe any plan to support it some day? Should it live on another repository, or are PRs accepted?

**Comment by xlcnd** [comment]
Hi,

ISSN is not supported by `isbnlib` and it will not be supported in the future! Why? Because despite the similarities in the name, it needs a very different strategy to collect metadata. 

However, there are python libraries that validate ISSN ([python-stdnum](https://github.com/arthurdejong/python-stdnum)) and fetch metadata ([arxiv.py](https://pypi.org/project/arxiv/), [pubmed-lookup](https://pypi.org/project/pubmed-lookup/), ... and many others).

Thanks.
